package com.powernow.cdt.dao;

import com.powernow.cdt.model.OcBannerImage;
import java.util.List;

public interface OcBannerImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_banner_image
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer bannerImageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_banner_image
     *
     * @mbggenerated
     */
    int insert(OcBannerImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_banner_image
     *
     * @mbggenerated
     */
    OcBannerImage selectByPrimaryKey(Integer bannerImageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_banner_image
     *
     * @mbggenerated
     */
    List<OcBannerImage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_banner_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OcBannerImage record);



    List<OcBannerImage> selectByBannerIdAndLangId(Integer banner_id,Integer langId);
}