package com.powernow.cdt.dao;

import com.powernow.cdt.model.OcLanguage;
import java.util.List;

public interface OcLanguageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_language
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer languageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_language
     *
     * @mbggenerated
     */
    int insert(OcLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_language
     *
     * @mbggenerated
     */
    OcLanguage selectByPrimaryKey(Integer languageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_language
     *
     * @mbggenerated
     */
    List<OcLanguage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_language
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OcLanguage record);


    OcLanguage selectByCode(String code);
}