package com.powernow.cdt.dao;

import com.powernow.cdt.model.OcModule;

import java.util.List;

public interface OcModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_module
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_module
     *
     * @mbggenerated
     */
    int insert(OcModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_module
     *
     * @mbggenerated
     */
    OcModule selectByPrimaryKey(Integer moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_module
     *
     * @mbggenerated
     */
    List<OcModule> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_module
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OcModule record);


    List<OcModule> selectByCode(String code);

}