package com.powernow.cdt.model;

import java.io.Serializable;

public class OcBannerImage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_banner_image.banner_image_id
     *
     * @mbggenerated
     */
    private Integer bannerImageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_banner_image.banner_id
     *
     * @mbggenerated
     */
    private Integer bannerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_banner_image.language_id
     *
     * @mbggenerated
     */
    private Integer languageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_banner_image.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_banner_image.link
     *
     * @mbggenerated
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_banner_image.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_banner_image.sort_order
     *
     * @mbggenerated
     */
    private Integer sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oc_banner_image
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_banner_image.banner_image_id
     *
     * @return the value of oc_banner_image.banner_image_id
     *
     * @mbggenerated
     */
    public Integer getBannerImageId() {
        return bannerImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_banner_image.banner_image_id
     *
     * @param bannerImageId the value for oc_banner_image.banner_image_id
     *
     * @mbggenerated
     */
    public void setBannerImageId(Integer bannerImageId) {
        this.bannerImageId = bannerImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_banner_image.banner_id
     *
     * @return the value of oc_banner_image.banner_id
     *
     * @mbggenerated
     */
    public Integer getBannerId() {
        return bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_banner_image.banner_id
     *
     * @param bannerId the value for oc_banner_image.banner_id
     *
     * @mbggenerated
     */
    public void setBannerId(Integer bannerId) {
        this.bannerId = bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_banner_image.language_id
     *
     * @return the value of oc_banner_image.language_id
     *
     * @mbggenerated
     */
    public Integer getLanguageId() {
        return languageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_banner_image.language_id
     *
     * @param languageId the value for oc_banner_image.language_id
     *
     * @mbggenerated
     */
    public void setLanguageId(Integer languageId) {
        this.languageId = languageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_banner_image.title
     *
     * @return the value of oc_banner_image.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_banner_image.title
     *
     * @param title the value for oc_banner_image.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_banner_image.link
     *
     * @return the value of oc_banner_image.link
     *
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_banner_image.link
     *
     * @param link the value for oc_banner_image.link
     *
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_banner_image.image
     *
     * @return the value of oc_banner_image.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_banner_image.image
     *
     * @param image the value for oc_banner_image.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_banner_image.sort_order
     *
     * @return the value of oc_banner_image.sort_order
     *
     * @mbggenerated
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_banner_image.sort_order
     *
     * @param sortOrder the value for oc_banner_image.sort_order
     *
     * @mbggenerated
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_banner_image
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bannerImageId=").append(bannerImageId);
        sb.append(", bannerId=").append(bannerId);
        sb.append(", languageId=").append(languageId);
        sb.append(", title=").append(title);
        sb.append(", link=").append(link);
        sb.append(", image=").append(image);
        sb.append(", sortOrder=").append(sortOrder);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}