package com.powernow.cdt.model;

import java.io.Serializable;

public class OcLanguage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_language.language_id
     *
     * @mbggenerated
     */
    private Integer languageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_language.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_language.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_language.locale
     *
     * @mbggenerated
     */
    private String locale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_language.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_language.directory
     *
     * @mbggenerated
     */
    private String directory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_language.sort_order
     *
     * @mbggenerated
     */
    private Integer sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_language.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oc_language
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_language.language_id
     *
     * @return the value of oc_language.language_id
     *
     * @mbggenerated
     */
    public Integer getLanguageId() {
        return languageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_language.language_id
     *
     * @param languageId the value for oc_language.language_id
     *
     * @mbggenerated
     */
    public void setLanguageId(Integer languageId) {
        this.languageId = languageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_language.name
     *
     * @return the value of oc_language.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_language.name
     *
     * @param name the value for oc_language.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_language.code
     *
     * @return the value of oc_language.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_language.code
     *
     * @param code the value for oc_language.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_language.locale
     *
     * @return the value of oc_language.locale
     *
     * @mbggenerated
     */
    public String getLocale() {
        return locale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_language.locale
     *
     * @param locale the value for oc_language.locale
     *
     * @mbggenerated
     */
    public void setLocale(String locale) {
        this.locale = locale == null ? null : locale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_language.image
     *
     * @return the value of oc_language.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_language.image
     *
     * @param image the value for oc_language.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_language.directory
     *
     * @return the value of oc_language.directory
     *
     * @mbggenerated
     */
    public String getDirectory() {
        return directory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_language.directory
     *
     * @param directory the value for oc_language.directory
     *
     * @mbggenerated
     */
    public void setDirectory(String directory) {
        this.directory = directory == null ? null : directory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_language.sort_order
     *
     * @return the value of oc_language.sort_order
     *
     * @mbggenerated
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_language.sort_order
     *
     * @param sortOrder the value for oc_language.sort_order
     *
     * @mbggenerated
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_language.status
     *
     * @return the value of oc_language.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_language.status
     *
     * @param status the value for oc_language.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_language
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", languageId=").append(languageId);
        sb.append(", name=").append(name);
        sb.append(", code=").append(code);
        sb.append(", locale=").append(locale);
        sb.append(", image=").append(image);
        sb.append(", directory=").append(directory);
        sb.append(", sortOrder=").append(sortOrder);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}